import { useState } from 'react'
import { Download, CheckCircle2, AlertCircle, Loader2, FileText, Users, Layers, Circle, LayoutGrid, Presentation } from 'lucide-react'
import JSZip from 'jszip'
import { cn } from '@/lib/utils'
import { hasStartupOverview, loadStartupOverview } from '@/lib/startup-loader'
import { hasLeanCanvas, loadLeanCanvas } from '@/lib/canvas-loader'
import { hasGoldenCircle, loadGoldenCircle } from '@/lib/golden-circle-loader'
import { hasPersonas, loadPersonas } from '@/lib/personas-loader'
import { hasValueProposition, loadValueProposition } from '@/lib/value-prop-loader'
import { hasPitchDeck, loadPitchDeck } from '@/lib/pitch-deck-loader'
import EmptyState from '@/components/EmptyState'

// ─── File checklist item ───────────────────────────────────────────────────

interface ChecklistItem {
  label: string
  description: string
  command: string
  present: boolean
  required: boolean
  icon: React.ReactNode
}

function FileRow({ item }: { item: ChecklistItem }) {
  return (
    <div className="flex items-start gap-3 py-3">
      <div
        className={cn(
          'mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg',
          item.present
            ? 'bg-emerald-100 text-emerald-600 dark:bg-emerald-900/30 dark:text-emerald-400'
            : item.required
              ? 'bg-red-50 text-red-400 dark:bg-red-900/20 dark:text-red-500'
              : 'bg-slate-100 text-slate-400 dark:bg-slate-800 dark:text-slate-500',
        )}
      >
        {item.icon}
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <p className="text-sm font-medium text-slate-900 dark:text-slate-100">{item.label}</p>
          {item.required && !item.present && (
            <span className="rounded-full bg-red-100 px-1.5 py-0.5 font-mono text-[9px] font-semibold uppercase tracking-wider text-red-600 dark:bg-red-900/40 dark:text-red-400">
              required
            </span>
          )}
        </div>
        <p className="text-xs text-slate-500 dark:text-slate-400">{item.description}</p>
      </div>
      <div className="shrink-0">
        {item.present ? (
          <CheckCircle2 className="h-4 w-4 text-emerald-500" />
        ) : (
          <code className="font-mono text-[10px] text-slate-300 dark:text-slate-700">
            {item.command}
          </code>
        )}
      </div>
    </div>
  )
}

// ─── Export helpers ─────────────────────────────────────────────────────────

async function buildZip(): Promise<Blob> {
  const zip = new JSZip()
  const plan = zip.folder('startup-plan')!

  const overview = loadStartupOverview()
  const canvas = loadLeanCanvas()
  const gc = loadGoldenCircle()
  const personas = loadPersonas()
  const vp = loadValueProposition()
  const deck = loadPitchDeck()

  // README
  const startupName = overview?.name ?? 'My Startup'
  plan.file(
    'README.md',
    `# ${startupName} — Startup Plan\n\nGenerated by Startup Lab.\n\n## Files\n\n- \`executive-summary.md\` — Overview and key metrics\n- \`lean-canvas.md\` — Business model canvas\n- \`golden-circle.md\` — Purpose and GTM strategy\n- \`value-proposition.md\` — Customer / value fit\n- \`personas/\` — Target customer profiles\n- \`pitch-deck/slides.md\` — 10-slide pitch deck\n`,
  )

  // Executive summary
  if (overview) {
    plan.file(
      'executive-summary.md',
      `# ${overview.name} — Executive Summary\n\n**Stage:** ${overview.stage}\n${overview.industry ? `**Industry:** ${overview.industry}\n` : ''}${overview.teamSize ? `**Team:** ${overview.teamSize}\n` : ''}\n## Tagline\n${overview.tagline ?? ''}\n\n## Problem\n${overview.problem ?? ''}\n\n## Target Market\n${overview.targetMarket ?? ''}\n`,
    )
  }

  // Lean canvas
  if (canvas) {
    plan.file(
      'lean-canvas.md',
      `# Lean Canvas\n\n## Problem\n${canvas.problem}\n\n## Customer Segments\n${canvas.customerSegments}\n\n## Unique Value Proposition\n${canvas.uniqueValueProposition}\n\n## Solution\n${canvas.solution}\n\n## Channels\n${canvas.channels}\n\n## Revenue Streams\n${canvas.revenueStreams}\n\n## Cost Structure\n${canvas.costStructure}\n\n## Key Metrics\n${canvas.keyMetrics}\n\n## Unfair Advantage\n${canvas.unfairAdvantage}\n`,
    )
  }

  // Golden circle
  if (gc) {
    plan.file(
      'golden-circle.md',
      `# Golden Circle\n\n## Why\n${gc.why}\n\n## How\n${gc.how}\n\n## What\n${gc.what}\n\n## Go-to-Market Strategy\n\n### Target Market\n${gc.gtm.targetMarket}\n\n### Value Proposition\n${gc.gtm.valueProposition}\n\n### Pricing Strategy\n${gc.gtm.pricingStrategy}\n\n### Distribution Channels\n${gc.gtm.distributionChannels}\n\n### Marketing Strategy\n${gc.gtm.marketingStrategy}\n\n### Key Metrics\n${gc.gtm.keyMetrics}\n`,
    )
  }

  // Value proposition
  if (vp) {
    const fmt = (arr: string[]) => arr.map((s) => `- ${s}`).join('\n')
    plan.file(
      'value-proposition.md',
      `# Value Proposition Canvas\n\n## Customer Profile\n\n### Customer Jobs\n${fmt(vp.customerProfile.customerJobs)}\n\n### Customer Gains\n${fmt(vp.customerProfile.customerGains)}\n\n### Customer Pains\n${fmt(vp.customerProfile.customerPains)}\n\n## Value Map\n\n### Products & Services\n${fmt(vp.valueMap.products)}\n\n### Gain Creators\n${fmt(vp.valueMap.gainCreators)}\n\n### Pain Relievers\n${fmt(vp.valueMap.painRelievers)}\n`,
    )
  }

  // Personas
  if (personas.length > 0) {
    const personasFolder = plan.folder('personas')!
    for (const p of personas) {
      const fmt = (arr: string[]) => arr.map((s) => `- ${s}`).join('\n')
      personasFolder.file(
        `${p.id}.md`,
        `# ${p.name}\n\n**Age:** ${p.age > 0 ? p.age : 'N/A'}\n**Occupation:** ${p.occupation}\n${p.location ? `**Location:** ${p.location}\n` : ''}${p.income ? `**Income:** ${p.income}\n` : ''}${p.techSavviness ? `**Tech Savviness:** ${p.techSavviness}\n` : ''}\n## About\n${p.description}\n\n${p.quote ? `> "${p.quote}"\n\n` : ''}## Goals\n${fmt(p.goals)}\n\n## Pain Points\n${fmt(p.painPoints)}\n\n${p.motivations.length > 0 ? `## Motivations\n${fmt(p.motivations)}\n\n` : ''}${p.preferredChannels.length > 0 ? `## Preferred Channels\n${fmt(p.preferredChannels)}\n` : ''}`,
      )
    }
  }

  // Pitch deck
  if (deck && deck.slides.length > 0) {
    const pitchFolder = plan.folder('pitch-deck')!
    const slidesContent = deck.slides
      .map((s, i) => `## Slide ${i + 1}: ${s.title}\n\n${s.content}`)
      .join('\n\n---\n\n')
    pitchFolder.file('slides.md', `# Pitch Deck\n\n${slidesContent}\n`)
  }

  return zip.generateAsync({ type: 'blob' })
}

// ─── Page ────────────────────────────────────────────────────────────────────

export default function ExportPage() {
  const [downloading, setDownloading] = useState(false)
  const [done, setDone] = useState(false)

  const overviewPresent = hasStartupOverview()
  const canvasPresent = hasLeanCanvas()

  const items: ChecklistItem[] = [
    {
      label: 'Startup Vision',
      description: 'startup/startup-overview.md',
      command: '/startup-vision',
      present: overviewPresent,
      required: true,
      icon: <FileText className="h-3.5 w-3.5" />,
    },
    {
      label: 'Lean Canvas',
      description: 'startup/lean-canvas/lean-canvas.md',
      command: '/lean-canvas',
      present: canvasPresent,
      required: true,
      icon: <LayoutGrid className="h-3.5 w-3.5" />,
    },
    {
      label: 'Golden Circle',
      description: 'startup/golden-circle/golden-circle.md',
      command: '/golden-circle',
      present: hasGoldenCircle(),
      required: false,
      icon: <Circle className="h-3.5 w-3.5" />,
    },
    {
      label: 'Personas',
      description: 'startup/personas/personas.json',
      command: '/create-persona',
      present: hasPersonas(),
      required: false,
      icon: <Users className="h-3.5 w-3.5" />,
    },
    {
      label: 'Value Proposition',
      description: 'startup/value-proposition/value-proposition.md',
      command: '/value-proposition',
      present: hasValueProposition(),
      required: false,
      icon: <Layers className="h-3.5 w-3.5" />,
    },
    {
      label: 'Pitch Deck',
      description: 'startup/pitch-deck/pitch-deck.md',
      command: '/generate-pitch-deck',
      present: hasPitchDeck(),
      required: false,
      icon: <Presentation className="h-3.5 w-3.5" />,
    },
  ]

  const requiredMissing = items.filter((i) => i.required && !i.present)
  const canExport = requiredMissing.length === 0

  async function handleDownload() {
    if (!canExport || downloading) return
    setDownloading(true)
    setDone(false)
    try {
      const blob = await buildZip()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = 'startup-plan.zip'
      a.click()
      URL.revokeObjectURL(url)
      setDone(true)
    } finally {
      setDownloading(false)
    }
  }

  if (!overviewPresent && !canvasPresent) {
    return (
      <EmptyState
        icon={<Download className="h-6 w-6" />}
        title="Nothing to export yet"
        description="Complete at least your Startup Vision and Lean Canvas before exporting."
        command="/startup-vision"
      />
    )
  }

  const completedCount = items.filter((i) => i.present).length

  return (
    <div className="mx-auto max-w-2xl px-6 py-8 space-y-8">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-slate-100">
            Export Startup Plan
          </h1>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
            Package everything into a portable zip archive
          </p>
        </div>
        <code className="mt-1 font-mono text-[11px] text-slate-400">/export-startup</code>
      </div>

      {/* File checklist */}
      <div className="rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">
        {/* Header row */}
        <div className="flex items-center justify-between border-b border-slate-200 px-4 py-3 dark:border-slate-800">
          <p className="font-mono text-[10px] uppercase tracking-wider text-slate-400">
            Files
          </p>
          <span className="font-mono text-[10px] text-slate-400">
            {completedCount} / {items.length}
          </span>
        </div>
        <div className="divide-y divide-slate-100 px-4 dark:divide-slate-800">
          {items.map((item) => (
            <FileRow key={item.label} item={item} />
          ))}
        </div>
      </div>

      {/* Warning if missing recommended */}
      {canExport && items.some((i) => !i.required && !i.present) && (
        <div className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 dark:border-amber-900/40 dark:bg-amber-900/10">
          <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-amber-500" />
          <p className="text-sm text-amber-700 dark:text-amber-400">
            Some optional files are missing. The export will still work but may be incomplete.
          </p>
        </div>
      )}

      {/* Download button */}
      <div className="flex flex-col items-start gap-3">
        <button
          onClick={handleDownload}
          disabled={!canExport || downloading}
          className={cn(
            'flex items-center gap-2.5 rounded-xl px-5 py-3 text-sm font-semibold transition-all',
            canExport
              ? 'bg-slate-900 text-white hover:bg-slate-800 active:scale-[0.98] dark:bg-slate-100 dark:text-slate-900 dark:hover:bg-slate-200'
              : 'cursor-not-allowed bg-slate-100 text-slate-400 dark:bg-slate-800 dark:text-slate-600',
          )}
        >
          {downloading ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : done ? (
            <CheckCircle2 className="h-4 w-4 text-emerald-500" />
          ) : (
            <Download className="h-4 w-4" />
          )}
          {downloading ? 'Building archive…' : done ? 'Downloaded!' : 'Download startup-plan.zip'}
        </button>

        {!canExport && (
          <p className="text-xs text-slate-400">
            Complete the required files above to enable export.
          </p>
        )}

        {done && (
          <p className="text-xs text-emerald-600 dark:text-emerald-400">
            startup-plan.zip saved to your downloads folder.
          </p>
        )}
      </div>

      {/* Contents preview */}
      <div className="space-y-2">
        <p className="font-mono text-[10px] uppercase tracking-wider text-slate-400">
          Archive contents
        </p>
        <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-900">
          <pre className="font-mono text-[11px] leading-relaxed text-slate-500 dark:text-slate-400">
{`startup-plan/
├── README.md
├── executive-summary.md${hasLeanCanvas() ? '\n├── lean-canvas.md' : ''}${hasGoldenCircle() ? '\n├── golden-circle.md' : ''}${hasValueProposition() ? '\n├── value-proposition.md' : ''}${hasPersonas() ? `\n├── personas/\n│   └── [${loadPersonas().length} file${loadPersonas().length !== 1 ? 's' : ''}]` : ''}${hasPitchDeck() ? '\n└── pitch-deck/\n    └── slides.md' : ''}`}
          </pre>
        </div>
      </div>
    </div>
  )
}
