#!/usr/bin/env bash
# set-profile.sh — switch the active startup profile
# Usage: ./scripts/set-profile.sh <profile>
# Profiles: base | saas | marketplace | b2b | consumer | hardware

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# ── Usage ─────────────────────────────────────────────────────────────────────
usage() {
  echo ""
  bold "  Usage: ./scripts/set-profile.sh <profile>"
  echo ""
  echo "  Available profiles:"
  for p in "${VALID_PROFILES[@]}"; do
    local desc=""
    case "$p" in
      base)        desc="Universal defaults — no startup-type overrides" ;;
      saas)        desc="Subscription software, PLG, MRR/churn metrics" ;;
      marketplace) desc="Two-sided platforms, GMV, liquidity, cold start" ;;
      b2b)         desc="Business sales, ACV, sales cycles, ICP" ;;
      consumer)    desc="Consumer apps, retention loops, virality, habit formation" ;;
      hardware)    desc="Physical products, BOM, manufacturing stages" ;;
    esac
    echo -e "    ${BOLD}${p}${RESET}  —  ${DIM}${desc}${RESET}"
  done
  echo ""
  exit 1
}

[[ $# -lt 1 ]] && usage

NEW_PROFILE="$1"

# ── Validate ──────────────────────────────────────────────────────────────────
if ! is_valid_profile "$NEW_PROFILE"; then
  error "Unknown profile: '$NEW_PROFILE'"
  usage
fi

PROFILE_FILE="$PROFILES_DIR/${NEW_PROFILE}.md"
if [[ ! -f "$PROFILE_FILE" ]]; then
  error "Profile file not found: profiles/${NEW_PROFILE}.md"
  exit 1
fi

# ── Update or create index ────────────────────────────────────────────────────
TODAY="$(date +%Y-%m-%d)"

if [[ -f "$INDEX_FILE" ]]; then
  CURRENT="$(yaml_get "profile")"

  if [[ "$CURRENT" == "$NEW_PROFILE" ]]; then
    info "Profile is already set to '${NEW_PROFILE}'."
    exit 0
  fi

  # Update the profile line in-place
  sed -i "s/^profile:.*/profile: ${NEW_PROFILE}/" "$INDEX_FILE"
  # Update last_updated
  sed -i "s/^last_updated:.*/last_updated: \"${TODAY}\"/" "$INDEX_FILE"

  success "Profile changed: ${BOLD}${CURRENT}${RESET} → ${BOLD}${NEW_PROFILE}${RESET}"
else
  # No index yet — create a minimal one with the chosen profile
  warn "No startup/index.yml found. Creating a minimal index..."
  mkdir -p "$STARTUP_DIR"
  cat > "$INDEX_FILE" <<EOF
# Auto-generated by Startup OS. Do not edit manually.
version: 1
last_updated: "${TODAY}"
profile: ${NEW_PROFILE}

startup:
  name: ""
  stage: ""
  industry: ""

files:
  overview:
    path: startup/startup-overview.md
    present: false
  lean_canvas:
    path: startup/lean-canvas/lean-canvas.md
    present: false
    sections_complete: 0
    sections_total: 9
  golden_circle:
    path: startup/golden-circle/golden-circle.md
    present: false
  personas:
    path: startup/personas/personas.json
    present: false
    count: 0
  value_proposition:
    path: startup/value-proposition/value-proposition.md
    present: false
  pitch_deck:
    path: startup/pitch-deck/pitch-deck.md
    present: false
    slides_complete: 0
    slides_total: 10

progress:
  completed: 0
  total: 6
  next_step: /startup-vision
EOF
  success "Created startup/index.yml with profile: ${BOLD}${NEW_PROFILE}${RESET}"
fi

echo ""
dim "  Profile file: profiles/${NEW_PROFILE}.md"
dim "  The next Claude Code session will apply ${NEW_PROFILE}-specific coaching."
echo ""
